# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://ple103.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "ple103"
copyright = "&copy; 2022 Peter Le"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

[author]
  name = "Peter Le"
  image = "img/author.jpg"
# bio = "A little bit about you"
  links = [
    { email = "mailto:hello@ple103.com" },
    { github = "https://github.com/ple103" },
    { gitlab = "https://gitlab.com/ple103" },
    { instagram = "https://instagram.com/ple103" },
    { keybase = "https://keybase.io/ple103" },
    { linkedin = "https://linkedin.com/in/ple103" },
  ]

[params]
colorScheme = "congo"
darkMode = "auto"
darkToggle = true
logo = "img/logo.png"
description = "Landing page and internet home of Pete / ple103."
# mainSections = ["section1", "section2"]
robots = "noindex"

[params.homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

[params.article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[params.list]
  showBreadcrumbs = true
  showSummary = true
  groupByYear = true

[params.taxonomy]
  showTermCount = true

[params.sitemap]
  excludedKinds = ["taxonomy", "term"]

[params.fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[params.verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[[menu.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[menu.main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[menu.main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
